homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('education/', views.education, name='education'),
    path('experience/', views.experience, name='experience'),
    path('skills/', views.skills, name='skills'),
    path('schedule/', views.schedule1, name='schedule'),
    path('create_schedule/', views.create_schedule, name='create_schedule'),
    path('schedule_delete/', views.schedule_delete, name='schedule_delete'),
    path('contact/', views.contact, name='contact'),
]

story/urls.py
from django.urls import path, include
from django.contrib import admin


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls', namespace='homepage')),
]

homepage/models.py
from django.db import models
from datetime import datetime

# Create your models here.

class Schedule(models.Model):

    activity = models.CharField(max_length=30)
    date = models.DateTimeField(default=datetime.now)
    time = models.TimeField()
    place = models.CharField(max_length=20)
    category = models.CharField(max_length=20)

    def __str__(self):
        return self.activity

story/models.py
from django.db import models

class Jadwal(models.Model):
	DAY_CHOICES = (
		('Mon', 'Monday'),
		('Tue','Tuesday'),
		('Wed','Wednesday'),
		('Thu','Thursday'),
		('Fri','Friday'),
		('Sat','Saturday'),
		('Sun','Sunday')
		)

	day = models.CharField(choices=DAY_CHOICES, max_length=20)
	date = models.DateField()
	time = models.TimeField()
	name = models.CharField(max_length=30)
	location = models.CharField(max_length=30)
	category = models.CharField(max_length=20)

homepage/forms.py
from django import forms
from .models import Schedule


class ScheduleForm(forms.ModelForm):
    class Meta:
        model = Schedule
        fields = ['activity', 'date', 'time', 'place', 'category']
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'}),
            'time': forms.TimeInput(attrs={'type': 'time'})}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.Meta.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

homepage/views.py
from django.shortcuts import render, redirect
from .models import Schedule
from . import forms
from django.http import HttpResponse


# Create your views here.
def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def education(request):
    return render(request, 'education.html')

def experience(request):
    return render(request, 'experience.html')

def skills(request):
    return render(request, 'skills.html')

def schedule1(request):
    schedules = Schedule.objects.all().order_by('date')
    return render(request, 'schedule.html', {'schedules': schedules})

def create_schedule(request):
    if request.method == 'POST':
        form = forms.ScheduleForm(request.POST)
        print(request.POST)
        if form.is_valid():
            form.save()
            print(Schedule.objects.all())
            return redirect('homepage:schedule')
    else:
        form = forms.ScheduleForm()
    return render(request, 'create_schedule.html', {'form': form})

def schedule_delete(request):
	Schedule.objects.all().delete()
	return redirect('homepage:schedule')

def contact(request):
    return render(request, 'contact.html')

story/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.template import Context, loader
from .forms import JadwalKegiatan
from .models import Jadwal

def index(request):
	return render(request, 'story3.html')
	
def form(request):
	return render(request, 'form.html')
	
def art(request):
	return render(request, 'story3one.html')

def show_schedule(request):
    response = {}
    jadwal = Jadwal.objects.all()
    response = {
        "jadwal" : jadwal
    }
    return render(request, 'showschedule.html', response)


def schedule(request):
	form = JadwalKegiatan(request.POST or None)
	response = {}
	if(request.method == "POST"):
		if (form.is_valid()):
			day = request.POST.get("day")
			date = request.POST.get("date")
			time = request.POST.get("time")
			name = request.POST.get("name")
			location = request.POST.get("location")
			category = request.POST.get("category")
			Jadwal.objects.create(day=day, date=date, time=time, name=name, location=location, category=category)
			return redirect('show_schedule')
		else:
			response['form'] = form
			return render(request, 'schedule.html', response)
	else:
		response['form'] = form
		return render(request, 'schedule.html', response)

def delete(request):
    jadwal = Jadwal.objects.all().delete()
    return redirect('show_schedule')


# Create your views here.

homepage/templates/about.html
{% extends 'base.html' %}
<!DOCTYPE html>
{% load static %}
<!-- <html lang="en">
<head>
    <title>kamila alifia's personal page</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Abril+Fatface|Dancing+Script|Lora|Playfair+Display|Tenali+Ramakrishna&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head> -->
{% block content %}
<body>
    <!-- <div class="box1">
        <nav class="navbar">
            <ul class="navbtn">
                <a href="{% url 'homepage:home' %}"><li>HOME</li></a>
                <a href="{% url 'homepage:about' %}"><li>ABOUT</li></a>
                <a href="{% url 'homepage:education' %}"><li>EDUCATION</li></a>
                <a href="{% url 'homepage:experience' %}"><li>EXPERIENCES</li></a>
                <a href="{% url 'homepage:skills' %}"><li>SKILLS</li></a>
                <a href="{% url 'homepage:contact' %}"><li>CONTACT</li></a>
            </ul>
            <div id="logo"><img src="{% static 'images/KamilaLogo.png' %}" width="70px" height="60px"></div>
        </nav>
    </div> -->
    <div id="pageabout" style="padding-top:65px" >
        <div class=row>
            <div class="col-12 col-md-8">
                <div id="t1">GET TO KNOW HER BETTER</div>
                <p>
                    <br>Hi, nice to see you there! This page belongs to Kamila Alifia, but you can call her Kamila for short. She claimed herself as a full-time college student and a part-time dreamer.</br>
                    <br>Oh, and also a learner who is well-organized and has a strong will, ready to face challenges to reach her dreams and dare to experience fail in order to achieve victory. She has a passion in the fields of business, information & technology, and creative industries.</br>
                    <br>Her interest including fashion, beauty, health and lifestyle. She is calm, but passionate to learn new things. She is indeed a compassionately loving kind of person.</br>
                </p>
            </div>
            <div class="col-12 col-md-4">
                <img src="{% static 'images/Santorini.jpg' %}" width="100%" height="100%">
            </div>
        </div>
    </div>
</body>
{% endblock %}

homepage/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <title>kamila alifia's personal page</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Abril+Fatface|Dancing+Script|Lora|Playfair+Display|Tenali+Ramakrishna&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <div class="box1">
        <nav class="navbar">
            <ul class="navbtn">
                <a href="{% url 'homepage:home' %}"><li>HOME</li></a>
                <a href="{% url 'homepage:about' %}"><li>ABOUT</li></a>
                <a href="{% url 'homepage:education' %}"><li>EDUCATION</li></a>
                <a href="{% url 'homepage:experience' %}"><li>EXPERIENCES</li></a>
                <a href="{% url 'homepage:skills' %}"><li>SKILLS</li></a>
                <a href="{% url 'homepage:create_schedule' %}"><li>CREATE SCHEDULE</li></a>
                <a href="{% url 'homepage:schedule' %}"><li>SCHEDULE</li></a>
                <a href="{% url 'homepage:contact' %}"><li>CONTACT</li></a>
            </ul>
            <div id="logo"><img src="{% static 'images/KamilaLogo.png' %}" width="70px" height="60px"></div>
        </nav>
    </div>
{% block content %}
{% endblock %}
</body>
</html>

homepage/templates/contact.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <title>kamila alifia's personal page</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Abril+Fatface|Dancing+Script|Lora|Playfair+Display|Tenali+Ramakrishna&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
{% block content %}
<body>
    <div id="pagecontact" style="padding-top:100px; padding-bottom:30px;" class="container-fluid">
        <div class=row>
            <div class="col-7">
                <img src="{% static 'images/Desktop 8.png' %}" style="width:345px; height:370px; padding-bottom:70px;">
            </div>
            <div class="col-5"style="margin-top:80px;">
                <div class="row center social-logo"style="margin-bottom:30px;margin-left:40px;">
                    <a href="https://www.instagram.com/kamilaalifiaa/">
                        <img src="{% static 'images/instagramlogo.png' %}" alt="Instagram" style="width:64px;height:50px;border:0;filter:opacity(30%);">
                    </a>
                    <a href="https://www.linkedin.com/in/kamila-alifia/">
                        <img src="{% static 'images/linkedinlogo.png' %}" alt="LinkedIn" style="width:42px;height:42px;border:0;filter:opacity(30%);">
                    </a>
                    <a href="mailto:kamila.alifia@ui.ac.id? subject=Hi, I came from your website.">
                        <img src="{% static 'images/emaillogo.jpg' %}" alt="E-mail" style="width:53px;height:42px;border:0;filter:opacity(30%);">
                    </a>
                </div>
                <div class="row center contact-question" style="text-align: center">
                    <p style="padding: 0 0 0 0">If you have any further questions,<br>feel free to contact me.</br></p>
                </div>
            </div>
            <div class="container-fluid text-right">
                <a href="{% url 'homepage:home' %}">
                    <img src="{% static 'images/home.png' %}" style="position:absolute; width:80px; height:80px; border:0; top:70%; right:5%;">
                </a>
            </div>
        </div>
    </div>
    <div class="box2" style="bottom:0px;">
        <div id="copyright">copyright © 2019 by kamila alifia.</div>
    </div>
</body>
{% endblock %}

homepage/templates/create_schedule.html
{% extends 'base.html' %}
{% load static %}
{% block content %} 

    <form class="css" action="{% url 'homepage:create_schedule' %}" method="post" style="padding-top:130px;">
        {% csrf_token %}
        <div class="form-row">
            <div class="col-sm-1"></div>
            <div class="form-group col-sm-10">
                {% for fields in form %}
                    {{ fields.label_tag }}
                    <br>
                    {{ fields }}
                {% endfor %}
            </div>
        </div>
        <div class="form-row">
            <div class="col-sm-1"></div>
            <input type="submit" class="btn btn-primary float-right" value="Add">
        </form>
    {% endblock %}

homepage/templates/education.html
{% extends 'base.html' %}
<!DOCTYPE html>
{% load static %}
<!-- <html lang="en">
<head>
    <title>kamila alifia's personal page</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Abril+Fatface|Dancing+Script|Lora|Playfair+Display|Tenali+Ramakrishna&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head> -->
{% block content %}
<body>
    <!-- <div class="box1">
        <nav class="navbar">
            <ul class="navbtn">
                <a href="{% url 'homepage:home' %}"><li>HOME</li></a>
                <a href="{% url 'homepage:about' %}"><li>ABOUT</li></a>
                <a href="{% url 'homepage:education' %}"><li>EDUCATION</li></a>
                <a href="{% url 'homepage:experience' %}"><li>EXPERIENCES</li></a>
                <a href="{% url 'homepage:skills' %}"><li>SKILLS</li></a>
                <a href="{% url 'homepage:contact' %}"><li>CONTACT</li></a>
            </ul>
            <div id="logo"><img src="{% static 'images/KamilaLogo.png' %}" width="70px" height="60px"></div>
        </nav>
    </div> -->
    <div id="pageeducation">
        <div id="t2">HER LEARNING JOURNEY</div>
        <img src="{% static 'images/Group (2).png' %}" class="img-fluid" width="670px" height="360px">
    </div>
</body>
{% endblock %}

homepage/templates/experience.html
{% extends 'base.html' %}
<!DOCTYPE html>
{% load static %}
<!-- <html lang="en">
<head>
    <title>kamila alifia's personal page</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Abril+Fatface|Dancing+Script|Lora|Playfair+Display|Tenali+Ramakrishna&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head> -->
{% block content %}
<body>
    <!-- <div class="box1">
        <nav class="navbar">
            <ul class="navbtn">
                <a href="{% url 'homepage:home' %}"><li>HOME</li></a>
                <a href="{% url 'homepage:about' %}"><li>ABOUT</li></a>
                <a href="{% url 'homepage:education' %}"><li>EDUCATION</li></a>
                <a href="{% url 'homepage:experience' %}"><li>EXPERIENCES</li></a>
                <a href="{% url 'homepage:skills' %}"><li>SKILLS</li></a>
                <a href="{% url 'homepage:contact' %}"><li>CONTACT</li></a>
            </ul>
            <div id="logo"><img src="{% static 'images/KamilaLogo.png' %}" width="70px" height="60px"></div>
        </nav>
    </div> -->
    <div id="pageexperiences" style="padding-top: 150px" >
        <div class=row>
            <div class="col-7">
                <div id="t3">THINGS THAT SHE HAD EXPERIENCED</div>
                <a href="#committeeexperiences"><div id="t4"><br>COMMITTEE</br><br>EXPERIENCES</br></div></a>
                <a href="#workexperiences"><div id="t5"><br>WORK</br><br>EXPERIENCES</br></div></a>
            </div>
            <div class="col-5">
                <img src="{% static 'images/experiencequotes.JPG' %}" width="270px" height="450px">
            </div>
        </div>    
    </div>
    <div id="committeeexperiences" style="padding-top:90px; padding-left:3px;" >
        <div class="row">
            <img src="{% static 'images/Group.png' %}" class="img-fluid" width="700px" height="525px">
        </div>
    </div>
    <div id="workexperiences" style="padding-top:80px; margin-bottom:200px;" >
        <div class="row" style="float:right;">
            <img src="{% static 'images/Group (1).png' %}" class="img-fluid" width="700px" height="350px">
        </div>
    </div>
</body>
{% endblock %}

homepage/templates/home.html
{% extends 'base.html' %}
<!DOCTYPE html>
{% load static %}
<!-- <html lang="en">
<head>
    <title>kamila alifia's personal page</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Abril+Fatface|Dancing+Script|Lora|Playfair+Display|Tenali+Ramakrishna&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head> -->
{% block content %}
<body>
    <!-- <div class="box1">
        <nav class="navbar">
            <ul class="navbtn">
                <a href="{% url 'homepage:home' %}"><li>HOME</li></a>
                <a href="{% url 'homepage:about' %}"><li>ABOUT</li></a>
                <a href="{% url 'homepage:education' %}"><li>EDUCATION</li></a>
                <a href="{% url 'homepage:experience' %}"><li>EXPERIENCES</li></a>
                <a href="{% url 'homepage:skills' %}"><li>SKILLS</li></a>
                <a href="{% url 'homepage:contact' %}"><li>CONTACT</li></a>
            </ul>
            <div id="logo"><img src="{% static 'images/KamilaLogo.png' %}" width="70px" height="60px"></div>
        </nav>
    </div> -->
    <div id="pagehome">
        <div id="name">kamila alifia.</div>
        <div id="photo"><img src="{% static 'images/IMG_0514.jpg' %}" width="340px" height="500px"></div>
    </div>
</body>
{% endblock %}

homepage/templates/registration.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container backforms" style="padding-top: 120px;">
    <h2 class= "judul">Registration</h2>
  <form class="form-horizontal" action="/action_page.php">

       <div class="form-group row">
          <label for="nama" class="col-2 col-form-label">Nama:</label>
          <div class="col-10">
            <input class="form-control" type="text" id="nama">
          </div>
        </div>

      <div class="form-group row">
          <label for="datepicker" class="col-2 col-form-label">Tanggal Lahir:</label>
          <div class="col-10">
            <input id="datepicker" width="276" />
          </div>
        </div>

      <div class="form-group row">
          <label for="email" class="col-2 col-form-label">Email:</label>
          <div class="col-10">
            <input class="form-control" type="text" id="email">
          </div>
        </div>

      <div class="form-group row">
          <label for="username" class="col-2 col-form-label">Username:</label>
          <div class="col-10">
            <input class="form-control" type="username" id="username">
          </div>
        </div>
      <div class="form-group row">
          <label for="password" class="col-2 col-form-label">Password:</label>
          <div class="col-10">
            <input class="form-control" type="password" id="password">
          </div>
        </div>
      <div class="form-group row">
          <label for="password_conf" class="col-2 col-form-label">Password Confirmation:</label>
          <div class="col-10">
            <input class="form-control" type="password" id="password_conf">
          </div>
        </div>


  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-9">
      <button type="submit" class="btn btn-dark" disabled>Submit</button>
    </div>
  </div>
</form>
</div>

</body>
</html>
    <script>
        $('#datepicker').datepicker({
            uiLibrary: 'bootstrap4'
        });
    </script>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

{% endblock %}

homepage/templates/schedule.html
{% extends 'base.html' %}
{% load static %}
{% block content %} 
    <body>
        <h1 style="padding-top:100px; text-align: center">SCHEDULE</h1>
        <div class="article" style="padding-top:80px;">
            <a href="{% url 'homepage:schedule' %}"></a>
            <div class="article">
                <div class="row">
                    {% for schedule in schedules %}
                        <div class="col-sm-4 text-center">
                            <h2 class="act">{{ schedule.activity }}</h2>
                            <h3 class="desc">{{ schedule.description }}</h3>
                            <p>{{ schedule.date.date }}<br>
                                {{ schedule.time}}<br>
                                {{ schedule.place }}<br>
                                {{ schedule.category }}</p>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class = 'col-md-12'>
            <div class = 'form-group'>
                <a href="{% url 'homepage:schedule_delete' %}">
                    <button type="button" class= "btn btn-secondary btn-lg btn-sm">Clear</button>
                </a>
                <a href="{% url 'homepage:create_schedule' %}">
                    <button type="button" class= "btn btn-secondary btn-lg btn-sm">Create Another</button>
                </a>
        </div>
    </div>
    
    {% endblock %}
    </body>
    

homepage/templates/skills.html
{% extends 'base.html' %}
<!DOCTYPE html>
{% load static %}
<!-- <html lang="en">
<head>
    <title>kamila alifia's personal page</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Abril+Fatface|Dancing+Script|Lora|Playfair+Display|Tenali+Ramakrishna&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head> -->
{% block content %}
<body>
    <!-- <div class="box1">
        <nav class="navbar">
            <ul class="navbtn">
                <a href="{% url 'homepage:home' %}"><li>HOME</li></a>
                <a href="{% url 'homepage:about' %}"><li>ABOUT</li></a>
                <a href="{% url 'homepage:education' %}"><li>EDUCATION</li></a>
                <a href="{% url 'homepage:experience' %}"><li>EXPERIENCES</li></a>
                <a href="{% url 'homepage:skills' %}"><li>SKILLS</li></a>
                <a href="{% url 'homepage:contact' %}"><li>CONTACT</li></a>
            </ul>
            <div id="logo"><img src="{% static 'images/KamilaLogo.png' %}" width="70px" height="60px"></div>
        </nav>
    </div> -->
    <div id="pageskills" style="padding-top:55px;">
        <div class="row skills-title">
            <div id="t6">THINGS THAT SHE IS CAPABLE OF</div>
        </div>
        <div class="row skills-pic">
            <img src="{% static 'images/Desktop 7.png' %}" class="img-fluid" width="879px" height="520px">
        </div>
    </div>
</body>
{% endblock %}